# Generated by Django 4.0 on 2021-12-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nume', models.CharField(max_length=255)),
                ('firma', models.CharField(max_length=255)),
                ('calorii', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'articole',
            },
        ),
    ]
