# Generated by Django 4.0 on 2021-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articol',
            name='calorii',
            field=models.IntegerField(),
        ),
    ]
