# Generated by Django 4.0 on 2021-12-11 14:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caloriesApp', '0002_alter_articol_calorii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mancat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articole_mancate', models.ManyToManyField(to='caloriesApp.Articol')),
                ('utilizator', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mancat',
            },
        ),
    ]
