# Generated by Django 4.0 on 2021-12-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('caloriesApp', '0003_mancat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'utilizatori',
            },
        ),
        migrations.AlterField(
            model_name='mancat',
            name='utilizator',
            field=models.ManyToManyField(to='caloriesApp.Utilizator'),
        ),
    ]
