# Generated by Django 4.0 on 2021-12-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0005_alter_utilizator_utilizator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mancat',
            name='articole_mancate',
        ),
        migrations.AddField(
            model_name='mancat',
            name='articole_mancate',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='caloriesApp.articol'),
        ),
        migrations.RemoveField(
            model_name='mancat',
            name='utilizator',
        ),
        migrations.AddField(
            model_name='mancat',
            name='utilizator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='caloriesApp.utilizator'),
        ),
    ]
