# Generated by Django 4.0 on 2021-12-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('caloriesApp', '0007_mancat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancat',
            name='articole_mancate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='caloriesApp.articol'),
        ),
        migrations.AlterField(
            model_name='mancat',
            name='utilizator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Utilizator',
        ),
    ]
