# Generated by Django 4.0 on 2021-12-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('caloriesApp', '0008_alter_mancat_articole_mancate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mancat',
            name='articole_mancate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caloriesApp.articol'),
        ),
        migrations.AlterField(
            model_name='mancat',
            name='utilizator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
