# Generated by Django 4.0 on 2021-12-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0009_alter_mancat_articole_mancate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mancat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mancat',
            name='updated_at',
        ),
    ]
