# Generated by Django 4.0 on 2021-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0011_rename_utilizator_mancat_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancat',
            name='calorii',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
