# Generated by Django 4.0 on 2021-12-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0013_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
            ],
            options={
                'db_table': 'timp',
            },
        ),
    ]
