# Generated by Django 4.0 on 2021-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0014_timp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mancat',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
