# Generated by Django 4.0 on 2021-12-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesApp', '0015_mancat_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timp',
        ),
    ]
